export { default as Login } from "./Login/Login";
export { default as Lista } from "./Lista/Lista";
export { default as Modal } from "./Modal/Modal";
export { default as Carrito } from "./Carrito/Carrito";
export { default as ModalCarrito } from "./ModalCarrito/ModalCarrito";
export { default as SlideMenu } from "./slideMenu/SlideMenu";
export { default as Dashboard } from "./Dashboard/Dashboard";
export { default as Pedidos } from "./Pedidos/Pedidos";
export { default as AprepararGuardar } from "./AprepararGuardar/AprepararGuardar";
